version: "3"
services:
  react-app:
    image: react-app
    build: ./frontend/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - default
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=1
  api-server:
    image: api-server
    build: ./backend/
    stdin_open: true
    env_file: ./backend/config/${ENV}.env
    ports:
      - "4000:4000"
    networks:
      - default
    depends_on:
      - mongo
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo:4.4-bionic
    restart: "always"
    ports:
      - "27017:27017"
    networks:
      - default
    volumes:
      - mongo-data:/data/db
networks:
  default:
    driver: bridge
volumes:
  mongo-data:
    driver: local
